version: 2.1

workflows:
  workflow:
    jobs:
      - build
      - lint:
          requires:
            - build
      - unit_tests:
          requires:
            - build
      - instrumented_tests:
          requires:
            - build
      - deploy:
          requires:
            - lint
            - unit_tests
            - instrumented_tests
          filters:
            branches:
              only: release

executors:
  android-executor:
    docker:
      - image: cimg/android:2024.10
    resource_class: large
    environment:
      JVM_OPTS: -Xmx2048m
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+EnableDynamicAgentLoading" -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false
      CIRCLE_JDK_VERSION: openjdk21

jobs:
  build:
    working_directory: ~/code
    executor: android-executor
    steps:
      - prepare_environment
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies --no-daemon --build-cache
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-v2-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}

  lint:
    working_directory: ~/code
    executor: android-executor
    steps:
      - prepare_environment
      - run:
          name: Run Lint
          command: ./gradlew lint --no-daemon --build-cache
      - store_lint_artifacts

  unit_tests:
    working_directory: ~/code
    executor: android-executor
    steps:
      - prepare_environment
      - run:
          name: Run unit tests
          command: ./gradlew test --no-daemon --info --build-cache
          no_output_timeout: 15m
      - store_unit_test_results_and_artifacts

  instrumented_tests:
    machine:
      image: android:default
    resource_class: large
    steps:
      - prepare_environment
      - run:
          name: Create avd
          command: |
            SYSTEM_IMAGES="system-images;android-29;default;x86"
            sdkmanager "$SYSTEM_IMAGES"
            echo "no" | avdmanager --verbose create avd -n test -k "$SYSTEM_IMAGES"
      - run:
          name: Start ADB server
          command: |
            adb start-server
            adb devices
      - run:
          name: Launch emulator
          command: |
            emulator -avd test -delay-adb -verbose -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          background: true
      - run:
          # run in parallel with the emulator starting up, to optimize build time
          name: Run assembleDebugAndroidTest task
          command: |
            ./gradlew assembleDebugAndroidTest --no-daemon --build-cache
      - run:
          name: Wait for emulator to start
          command: |
            circle-android wait-for-boot
      - run:
          name: Disable emulator animations
          command: |
            adb shell settings put global window_animation_scale 0.0
            adb shell settings put global transition_animation_scale 0.0
            adb shell settings put global animator_duration_scale 0.0
      - run:
          name: Run UI tests (with retry)
          command: |
            MAX_TRIES=2
            run_with_retry() {
               n=1
               until [ $n -gt $MAX_TRIES ]
               do
                  echo "Starting test attempt $n"
                  ./gradlew connectedAndroidTest --no-daemon --build-cache && break
                  n=$[$n+1]
                  sleep 5
               done
               if [ $n -gt $MAX_TRIES ]; then
                 echo "Max tries reached ($MAX_TRIES)"
                 exit 1
               fi
            }
            run_with_retry
      - save_cache:
          key: gradle-v2-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      - store_android_test_results_and_artifacts

  deploy:
    executor: android-executor
    steps:
      - prepare_environment
      - run:
          name: Build Release
          command: |
            echo $ENCODED_KEYSTORE | base64 --decode >> ${HOME}/keystore.jks
            export KEYSTORE=${HOME}/keystore.jks
            ./gradlew clean assembleRelease --no-daemon --stacktrace --build-cache
      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: distribution
      - store_artifacts:
          path: app/build/outputs/mapping
          destination: distribution

commands:
  prepare_environment:
    description: "Common setup for all jobs"
    steps:
      - checkout
      - run:
          name: Generate Cache Key
          command: |
            find . -name 'build.gradle*' -o -name 'settings.gradle*' -o -name '*.toml' | sort | xargs cat | shasum | awk '{print $1}' > /tmp/gradle_cache_seed
      - restore_cache:
          key: gradle-v2-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}

  store_lint_artifacts:
    description: "Store Lint artifacts"
    steps:
      - store_artifacts:
          path: app/build/reports/lint-results-debug.html
          destination: app_lint_report
      - store_artifacts:
          path: core/build/reports/lint-results-debug.html
          destination: core_lint_report
      - store_artifacts:
          path: shared/build/reports/lint-results-debug.html
          destination: shared_lint_report
      - store_artifacts:
          path: widget/build/reports/lint-results-debug.html
          destination: widget_lint_report

  store_unit_test_results_and_artifacts:
    description: "Store Unit Test results and HTML reports"
    steps:
      - store_test_results:
          path: app/build/test-results/testDebugUnitTest
      - store_test_results:
          path: core/build/test-results/testDebugUnitTest
      - store_test_results:
          path: shared/build/test-results/testDebugUnitTest
      - store_test_results:
          path: widget/build/test-results/testDebugUnitTest
      - store_artifacts:
          path: app/build/reports/tests/testDebugUnitTest
          destination: app_unit_tests_report
      - store_artifacts:
          path: core/build/reports/tests/testDebugUnitTest
          destination: core_unit_tests_report
      - store_artifacts:
          path: shared/build/reports/tests/testDebugUnitTest
          destination: shared_unit_tests_report
      - store_artifacts:
          path: widget/build/reports/tests/testDebugUnitTest
          destination: widget_unit_tests_report

  store_android_test_results_and_artifacts:
    description: "Store Android Test results and HTML reports"
    steps:
      - store_test_results:
          path: shared/build/outputs/androidTest-results/connected/debug
      - store_test_results:
          path: app/build/outputs/androidTest-results/connected/debug
      - store_artifacts:
          path: app/build/reports/androidTests/connected
          destination: app_android_test_report
      - store_artifacts:
          path: shared/build/reports/androidTests/connected
          destination: shared_android_test_report
